name: Debian (standard)

images:
  # Debian + Hugo
  debian:
    target: debian
    alias:
      - $(VERSION)-debian
    tests:
      - hugo

  # Debian + Hugo + CI
  debian-ci:
    target: debian--ci
    alias:
      - $(VERSION)-debian-ci

  # Debian + Hugo + Onbuild
  debian-onbuild:
    target: debian--onbuild
    alias:
      - $(VERSION)-debian-onbuild

tests:
  hugo:
    command: version
    expected: hugo
